Deploy/50 update deploy scripts
RMI-PACTA/workflow.factset pull request #52
Opened 2024-02-16 14:01 UTC by AlexAxthelm

This PR updates t he deploy script and documentation, to account for changes in RMI's Azure infrastructure.

Of particular note is the `azure-deploy.rmi-pacta.parameters.json` file, which, if called as part of the `az deployment create` command (See updated README), will allow members of the RMI Active Directory with correct permissions (@cjyetman, @jdhoffa, and @AlexAxthelm ) to deploy a container instance which handle connecting to our Azure File Shares and deploying and authenticating to a Postgres database correctly, leaving`data_timestamp` and `iss_reporting_year` as the important parameters to be entered manually.

2024-02-16 14:02 UTC, AlexAxthelm commented
Suggested Review steps:

Execute the command in the "Deploy" Section of readme and see that the process proceeeds correctly (runs remotely, but takes ~12 hours)

2024-02-16 17:05 UTC, jdhoffa commented
When running the instructions for "Users with an RMI-PACTA Azure subscription", I get prompted for the following value:
<img width="1416" alt="Screenshot 2024-02-16 at 18 05 09" src="https://github.com/RMI-PACTA/workflow.factset/assets/8741309/ce21fc91-5ce2-4c08-ac7f-aa154699e248">

It's not clear to me what to set this to?

2024-02-19 10:07 UTC, AlexAxthelm commented
@jdhoffa updated docs. That parameter doesn't affect behavior, but is a label so you can manage the resources (container group & db), such as deleting them later, or finding them in the Azure Portal.

2024-02-20 16:07 UTC, jdhoffa requested changes
see comments

2024-02-20 16:53 UTC, AlexAxthelm commented
> Hey, so I get an error regarding the "refresh token"?

That one's new to me, but it looks like an error from `az`. I'm guessing here, but it looks like you took too long entering the parameters?

Try again with those same responses, but take less than 90 seconds this time?

2024-02-21 08:21 UTC, jdhoffa commented
I don't think that's it, I blazed through parameter setting that run to no avail:
<img width="693" alt="Screenshot 2024-02-21 at 09 20 49" src="https://github.com/RMI-PACTA/workflow.factset/assets/8741309/da34355b-eec1-48e9-a112-d64e232ede1b">

Note: it says the token was issued last year in August? Which is broadly in-line with the last time I was working with Azure? I wonder if I need to reset something on my account end?

2024-02-21 09:11 UTC, AlexAxthelm commented
Oh, then you probably need to refresh your credentials. `az login` (no flags, since you're trying to use your Azure Active Directory identity, not a system assigned one, which is why for our container running VMs, we use `az login --identity`, such as [here](https://github.com/RMI-PACTA/workflow.data.preparation/blob/665a67698c08700cca67637e2d087be641f9e403/README.md?plain=1#L161-L162))

2024-02-21 12:14 UTC, jdhoffa commented
Thank you! Seems to be running now. 
FYI. if you see a `containerGroup` on Azure called "jackson-test" that would be me :-)

2024-02-22 15:44 UTC, jdhoffa commented on README.md
>  This repo contains the `workflow.pacta` R package, a Dockerfile to build an image containing that package and its dependencies, and an Azure ARM template to deploy that image, along with [factset_dat
@AlexAxthelm

2024-02-22 15:48 UTC, jdhoffa approved these changes
I was able to trigger this locally, which then spins up two docker-containers under the `PACTA-RMI-SP-DEV` resource group. These docker containers spin-up:
* https://github.com/RMI-PACTA/factset_data_loader
* https://github.com/RMI-PACTA/workflow.factset

which in turn creates a PostgreSQL DB. Data is loaded into the DB by `factset_data_loader` and then processed in `R` by `workflow.factset` to our expected input datasets.

Final output is written to `PACTA-RMI-SP-PROD` resource group.

LGTM!

2024-02-22 16:43 UTC, jdhoffa approved these changes

2024-02-23 09:04 UTC, merged